# Generated by Django 3.1 on 2022-07-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterModelTable(
            name='admin',
            table='Admin_details',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='cartproduct',
            table='cart_product',
        ),
        migrations.AlterModelTable(
            name='category',
            table='catogery',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer_details',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
